### ISSUE TITLE
SpotifyWM no longer works on Manjaro with latest Spotify

### ISSUE THREAD

**Issue by Saboteur777** [dasJ/spotifywm#1]
SpotifyWM stopped working with latest Spotify on Manjaro. It might be related to the fact that now we have to install/compile libopenssl-1.0.0-compat for Spotify to work: https://aur.archlinux.org/packages/spotify/?comments=all

If I try to run Spotify with the command 
`LD_PRELOAD=/home/saboteur/.spotifywm/spotifywm.so /usr/share/spotify/spotify %U`
I got the following error: 
`/usr/share/spotify/spotify: /usr/lib/libssl.so.1.0.0: version "OPENSSL_1.0.0" not found (required by /usr/share/spotify/spotify)`
`/usr/share/spotify/spotify: /usr/lib/libcrypto.so.1.0.0: version "OPENSSL_1.0.0" not found (required by /usr/share/spotify/spotify)`
`/usr/share/spotify/spotify: /usr/lib/libcurl.so.4: version "CURL_OPENSSL_3" not found (required by /usr/share/spotify/spotify)`
Without SpotifyWM Spotify starts as it is intended, with the following output: 
`$ spotify `
`/usr/share/spotify/spotify: /usr/lib/libssl-compat.so.1.0.0: no version information available (required by /usr/share/spotify/spotify)`
`/usr/share/spotify/spotify: /usr/lib/libcrypto-compat.so.1.0.0: no version information available (required by /usr/share/spotify/spotify)`
`/usr/share/spotify/spotify: /usr/lib/libcurl-openssl-1.0.so: no version information available (required by /usr/share/spotify/spotify)`
`/usr/share/spotify/spotify: /usr/lib/libssl-compat.so.1.0.0: no version information available (required by /usr/lib/libcurl-openssl-1.0.so)`
`/usr/share/spotify/spotify: /usr/lib/libcrypto-compat.so.1.0.0: no version information available (required by /usr/lib/libcurl-openssl-1.0.so)`
`(spotify:8249): Gtk-WARNING **: Nem található a témamotor a következő modulútvonalon: „adwaita”,`
`(spotify:8249): Gtk-WARNING **: Nem található a témamotor a következő modulútvonalon: „adwaita”,`
`/usr/share/spotify/spotify: /usr/lib/libssl-compat.so.1.0.0: no version information available (required by /usr/share/spotify/spotify)`
`/usr/share/spotify/spotify: /usr/lib/libcrypto-compat.so.1.0.0: no version information available (required by /usr/share/spotify/spotify)`
`/usr/share/spotify/spotify: /usr/lib/libcurl-openssl-1.0.so: no version information available (required by /usr/share/spotify/spotify)`
`/usr/share/spotify/spotify: /usr/lib/libssl-compat.so.1.0.0: no version information available (required by /usr/lib/libcurl-openssl-1.0.so)`
`/usr/share/spotify/spotify: /usr/lib/libcrypto-compat.so.1.0.0: no version information available (required by /usr/lib/libcurl-openssl-1.0.so)`
`/proc/self/exe: /usr/lib/libssl-compat.so.1.0.0: no version information available (required by /proc/self/exe)`
`/proc/self/exe: /usr/lib/libcrypto-compat.so.1.0.0: no version information available (required by /proc/self/exe)`
`/proc/self/exe: /usr/lib/libcurl-openssl-1.0.so: no version information available (required by /proc/self/exe)`
`/proc/self/exe: /usr/lib/libssl-compat.so.1.0.0: no version information available (required by /usr/lib/libcurl-openssl-1.0.so)`
`/proc/self/exe: /usr/lib/libcrypto-compat.so.1.0.0: no version information available (required by /usr/lib/libcurl-openssl-1.0.so)`

**Comment by dasJ** [comment]
The Arch package modified `/usr/bin/spotify`, maybe you need to add the new changes to your own `LD_PRELOAD` line.

**Comment by Saboteur777** [comment]
I used to start Spotify with the following command, no more modifications were needed: 

`LD_PRELOAD=/usr/lib/libcurl.so.3:/home/saboteur/.spotifywm/spotifywm.so /usr/share/spotify/spotify %U`

What and how should I modify?

**Comment by dasJ** [comment]
Try:

```
LD_PRELOAD=libcrypto-compat.so.1.0.0:libssl-compat.so.1.0.0:libcurl-openssl-1.0.so:/path/to/spotifywm.so /usr/share/spotify/spotify %U
```

**Comment by Saboteur777** [comment]
You are awesome, thank you! 👍
