### ISSUE TITLE
Window content won't load until it is focused

### ISSUE THREAD

**Issue by kmarius** [dasJ/spotifywm#3]
Using i3 I can successfully start spotify on a different workspace using an `assign` rule. However the contents of the window won't load until it is focused.  This means I can not use for example `playerctl` to start playing music.

Does anyone know of a workaround?

**Comment by dasJ** [comment]
I suffer from the same problem, but I thought this was the normal spotify behaviour

**Comment by kmarius** [comment]
I found out today that spotify does now load properly and music can be started when it is launched in the background.
