### ISSUE TITLE
Not working in combination with dwm

### ISSUE THREAD

**Issue by hb0nes** [dasJ/spotifywm#6]
Hello sir, I only understand your code for 10% but at least the print statement is called;
```
~/Personal/spotifywm master !1 ?
❯ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libcurl.so.4:~/Personal/spotifywm/spotifywm
[spotifywm] attached to spotify
[spotifywm] attached to spotify
```
I also see this error, this might be related?
```
2020/04/17 15:41:22.068938 system_key.go:144: cannot determine seccomp compiler ve
036938bca13f96a666969d6d6 2.4.1 8c73f36d3de1f71977107bf6687514f16787f639058b4db4c6
```

However, unfortunately it does not work with dwm:
```
   35 static const Rule rules[] = {
   36     /* xprop(1):
   37      *  WM_CLASS(STRING) = instance, class
   38      *  WM_NAME(STRING) = title
   39      */
~  40     /* class             instance    title       tags mask     isfloating   isterminal noswallow monitor */
~  41     { "st",              NULL,       NULL,       0,            0,           1,         1,        -1 },
~  42     { "TelegramDesktop", NULL,       NULL,       1 << 1,       0,           0,         0,        -1 },
~  43     { "PrivMX",          NULL,       NULL,       1 << 2,       0,           0,         0,        -1 },
~  44     { "Spotify",         NULL,       NULL,       1 << 3,       0,           0,         0,        -1 },
+  45     { "Firefox",         NULL,       NULL,       1 << 8,       0,           0,         0,        -1 },
   46 };
```
It does not open on tab 4, as it should.

I'm pretty sure you're not going to maintain this but just thought I'd open the issue anyway, as it is one.

**Comment by aldoridhoni** [comment]
Strangely it works for me on Fedora with dwm.

`$ LD_PRELOAD=/home/user/spotifywm/spotifywm.so /usr/bin/spotify`

Spotify just open to designated tag.

**Comment by BachoSeven** [comment]
This works perfectly on ArchLinux, also using `dwm`. I simply use the convenient wrapper found in the [AUR](https://aur.archlinux.org/packages/spotifywm-git/), which does exactly what @aldoridhoni mentioned.

@hb0nes, can you report additional information such as what OS you're on?

**Comment by hb0nes** [comment]
I use latest Ubuntu, but if it's working for most then it's probably my fault. I just got used to opening this on a specific tab, no biggie. Closing issue.
